name: Node Build

on: [push]

jobs:
   mainbuild:
    runs-on: ${{ matrix.os }}
  
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [windows-latest, ubuntu-latest]
      
    steps:
      - uses: actions/checkout@v1
      
      - name: Print os with node-version
        run: echo The OS is ${{ matrix.os }} and Node Version is ${{ matrix.node-version }}
  
      - name: Run node.js on Windows and Ubuntu machines with 12 and 14 version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install npm and build
        run: | 
          npm ci
          npm run build
          npm test
      
